name: flutter_repoexplorer
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Core & Utils
  intl: ^0.20.2
  connectivity_plus: ^7.0.0
  get_it: ^9.2.0
  injectable: ^2.7.1+2
  logger: ^2.6.2

  # State Management & Data Class
  flutter_riverpod: ^3.0.3
  freezed_annotation: ^3.1.0

  # Networking
  dio: ^5.9.0
  json_annotation: ^4.9.0

  # Database
  drift: ^2.30.0
  sqlite3_flutter_libs: ^0.5.41

  # UI Components
  infinite_scroll_pagination: ^5.1.1
  cached_network_image: ^3.4.1
  go_router: ^17.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # Code Generation
  build_runner: ^2.10.4
  json_serializable: ^6.11.2
  drift_dev: ^2.30.0
  injectable_generator: ^2.9.1
  freezed: ^3.2.3

flutter:
  uses-material-design: true